console.log("first");
console.log("second");

try{
let a=10;
console.log("a is ",a)
}

catch(err){
    console.log(err)
}


console.log("third")

function test(){
    console.log("test is called")
}

test()